// Centralized icon re-exports so every usage in the app pulls from one place.
// We use lucide-react throughout; no emoji anywhere in the UI.
export {
  // Navigation
  LayoutDashboard,
  UtensilsCrossed,
  Utensils,
  Dumbbell,
  HeartPulse,
  Settings,
  Repeat,
  // Meals
  Coffee,
  Sun,
  Moon,
  Cookie,
  // Food / general actions
  Camera,
  ScanLine,
  Check,
  StickyNote,
  X,
  Plus,
  Minus,
  Trophy,
  Flame,
  Ruler,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Search,
  Calendar,
  Clock,
  Timer,
  MoreHorizontal,
  Pencil,
  Trash2,
  UserCircle,
  ArrowLeft,
  Delete,
  // Activity suggestions
  Footprints,
  Bike,
  Waves,
  Activity,
  Cog,
  PersonStanding,
  // Health stats
  TrendingDown,
  TrendingUp,
  Scale,
  CalendarCheck,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  // New pages / features
  BarChart2,
  Target,
  ChevronUp,
  Tag,
  Folder,
  Heart,
} from 'lucide-react'
